spring.application.name=ecmini
spring.profiles.active=local
spring.config.import=optional:classpath:application-secret.properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
spring.sql.init.encoding=UTF-8

logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.authentication=INFO
logging.level.com.example.ecmini=INFO

server.forward-headers-strategy=native
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true